### ISSUE TITLE
Register the package?

### ISSUE THREAD

**Issue by dmbates** [JuliaLinearAlgebra/RectangularFullPacked.jl#6]
@andreasnoack Shall we register this package?  I would prefer it to be registered so that we can depend on it in [MixedModels.jl](https://github.com/JuliaStats/MixedModels.jl).

**Comment by andreasnoack** [comment]
Sure. If you don't plan to make any further changes right now then let's go ahead and register it

**Comment by dmbates** [comment]
Good.  Will you do the submission please?  I always have to go back to the documentation and fumble around when trying to do an initial registration.

**Comment by ararslan** [comment]
https://github.com/JuliaRegistries/General/pull/68998

**Comment by andreasnoack** [comment]
Should be good to go now. It will be available in three days.
